import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import { academicYearsRouter } from './routes/academicYears.js';
import { staffRouter } from './routes/staff.js';
import { academicRouter } from './routes/academic.js';
import { staffAttendanceRouter } from './routes/staffAttendance.js';
import { payrollRouter } from './routes/payroll.js';
import { leaveRouter } from './routes/leave.js';
import { schoolProfileRouter } from './routes/schoolProfile.js';
import { examGradesRouter } from './routes/examGrades.js';
import { examTermsRouter } from './routes/examTerms.js';
import { observationParametersRouter } from './routes/observationParameters.js';
import { competencyParametersRouter } from './routes/competencyParameters.js';
import { examsRouter } from './routes/exams.js';
import { examAssessmentsRouter } from './routes/examAssessments.js';
import { examSchedulesRouter } from './routes/examSchedules.js';
import { examMarksRouter } from './routes/examMarks.js';
import { observationMarksRouter } from './routes/observationMarks.js';
import { competencyMarksRouter } from './routes/competencyMarks.js';
import { examResultsRouter } from './routes/examResults.js';
import { admitCardsRouter } from './routes/admitCards.js';
import { classTimingsRouter } from './routes/classTimings.js';
import { roomsRouter } from './routes/rooms.js';
import { timetablesRouter } from './routes/timetables.js';
import { registrationsRouter } from './routes/registrations.js';
import { authRouter } from './routes/auth.js';
import { enrollmentTypesRouter } from './routes/enrollmentTypes.js';
import { certificateTypesRouter } from './routes/certificateTypes.js';
import { booksRouter } from './routes/books.js';
import { libraryMembersRouter } from './routes/libraryMembers.js';
import { bookIssuesRouter } from './routes/bookIssues.js';
import { eBooksRouter } from './routes/eBooks.js';
import { studentAttendanceRouter } from './routes/studentAttendance.js';
import { hostelsRouter } from './routes/hostels.js';
import { hostelRoomsRouter } from './routes/hostelRooms.js';
import { roomAllocationsRouter } from './routes/roomAllocations.js';
import { hostelAttendanceRouter } from './routes/hostelAttendance.js';
import { hostelFeesRouter } from './routes/hostelFees.js';
import { messMenuRouter } from './routes/messMenu.js';
import { vehiclesRouter } from './routes/vehicles.js';
import { driversRouter } from './routes/drivers.js';
import { routesRouter } from './routes/routes.js';
import { transportAllocationsRouter } from './routes/transportAllocations.js';
import { transportFeesRouter } from './routes/transportFees.js';
import { suppliersRouter } from './routes/suppliers.js';
import { warehousesRouter } from './routes/warehouses.js';
import { inventoryCategoriesRouter } from './routes/inventoryCategories.js';
import { productsRouter } from './routes/products.js';
import { stockLedgersRouter } from './routes/stockLedgers.js';
import { purchasesRouter } from './routes/purchases.js';
import { salesRouter } from './routes/sales.js';
import { issuesRouter } from './routes/issues.js';
import { vendorsRouter } from './routes/vendors.js';
import { assetStoresRouter } from './routes/assetStores.js';
import { assetsRouter } from './routes/assets.js';
import { assetIssuesRouter } from './routes/assetIssues.js';
import { maintenanceRouter } from './routes/maintenance.js';
import { messagesRouter } from './routes/messages.js';
import { complaintTypesRouter } from './routes/complaintTypes.js';
import { complaintsRouter } from './routes/complaints.js';
import { emailConfigRouter } from './routes/emailConfig.js';
import { smsProviderConfigRouter } from './routes/smsProviderConfig.js';
import { sentEmailsRouter } from './routes/sentEmails.js';
import { sentSmsRouter } from './routes/sentSms.js';
import { eventsRouter } from './routes/events.js';
import { documentTypesRouter } from './routes/documentTypes.js';
import { studentDocumentsRouter } from './routes/studentDocuments.js';
import { staffDocumentsRouter } from './routes/staffDocuments.js';
import { backupRouter } from './routes/backup.js';
import { subjectMarkConfigRouter } from './routes/subjectMarkConfig.js';

const app = express();

app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.get('/health', (_req, res) => res.json({ ok: true }));
app.use('/api/auth', authRouter);
app.use('/api/academic-years', academicYearsRouter);
app.use('/api/staff', staffRouter);
app.use('/api/academic', academicRouter);
app.use('/api/staff-attendance', staffAttendanceRouter);
app.use('/api/payroll', payrollRouter);
app.use('/api/leave', leaveRouter);
app.use('/api/school-profile', schoolProfileRouter);
app.use('/api/exam-grades', examGradesRouter);
app.use('/api/exam-terms', examTermsRouter);
app.use('/api/observation-parameters', observationParametersRouter);
app.use('/api/competency-parameters', competencyParametersRouter);
app.use('/api/exams', examsRouter);
app.use('/api/exam-assessments', examAssessmentsRouter);
app.use('/api/exam-schedules', examSchedulesRouter);
app.use('/api/exam-marks', examMarksRouter);
app.use('/api/observation-marks', observationMarksRouter);
app.use('/api/competency-marks', competencyMarksRouter);
app.use('/api/exam-results', examResultsRouter);
app.use('/api/admit-cards', admitCardsRouter);
app.use('/api/class-timings', classTimingsRouter);
app.use('/api/rooms', roomsRouter);
app.use('/api/timetables', timetablesRouter);
app.use('/api/registrations', registrationsRouter);
app.use('/api/enrollment-types', enrollmentTypesRouter);
app.use('/api/certificate-types', certificateTypesRouter);
app.use('/api/books', booksRouter);
app.use('/api/library-members', libraryMembersRouter);
app.use('/api/book-issues', bookIssuesRouter);
app.use('/api/e-books', eBooksRouter);
app.use('/api/student-attendance', studentAttendanceRouter);
app.use('/api/hostels', hostelsRouter);
app.use('/api/hostel-rooms', hostelRoomsRouter);
app.use('/api/room-allocations', roomAllocationsRouter);
app.use('/api/hostel-attendance', hostelAttendanceRouter);
app.use('/api/hostel-fees', hostelFeesRouter);
app.use('/api/mess-menu', messMenuRouter);
app.use('/api/vehicles', vehiclesRouter);
app.use('/api/drivers', driversRouter);
app.use('/api/routes', routesRouter);
app.use('/api/transport-allocations', transportAllocationsRouter);
app.use('/api/transport-fees', transportFeesRouter);
app.use('/api/suppliers', suppliersRouter);
app.use('/api/warehouses', warehousesRouter);
app.use('/api/inventory-categories', inventoryCategoriesRouter);
app.use('/api/products', productsRouter);
app.use('/api/stock-ledgers', stockLedgersRouter);
app.use('/api/purchases', purchasesRouter);
app.use('/api/sales', salesRouter);
app.use('/api/issues', issuesRouter);
app.use('/api/vendors', vendorsRouter);
app.use('/api/asset-stores', assetStoresRouter);
app.use('/api/assets', assetsRouter);
app.use('/api/asset-issues', assetIssuesRouter);
app.use('/api/asset-maintenance', maintenanceRouter);
app.use('/api/messages', messagesRouter);
app.use('/api/complaint-types', complaintTypesRouter);
app.use('/api/complaints', complaintsRouter);
app.use('/api/email-config', emailConfigRouter);
app.use('/api/sms-provider-config', smsProviderConfigRouter);
app.use('/api/sent-emails', sentEmailsRouter);
app.use('/api/sent-sms', sentSmsRouter);
app.use('/api/events', eventsRouter);
app.use('/api/document-types', documentTypesRouter);
app.use('/api/student-documents', studentDocumentsRouter);
app.use('/api/staff-documents', staffDocumentsRouter);
app.use('/api/backup', backupRouter);
app.use('/api/subject-mark-config', subjectMarkConfigRouter);

const port = process.env.PORT || 5050;
const mongoUri = process.env.MONGODB_URI;
if (!mongoUri) {
  console.error('Missing MONGODB_URI. Create backend/.env from backend/.env.example');
  process.exit(1);
}

mongoose
  .connect(mongoUri)
  .then(() => {
    console.log('Connected to MongoDB');
    app.listen(port, () => console.log(`API listening on http://localhost:${port}`));
  })
  .catch((err) => {
    console.error('Mongo connection failed', err);
    process.exit(1);
  });

